// <auto-generated />
using System;
using FantasyApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(FantasyDbContext))]
    [Migration("20260402220326_InitialFantasy")]
    partial class InitialFantasy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FantasyApi.Models.CoachImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CoachImages");
                });

            modelBuilder.Entity("FantasyApi.Models.FantasyCoach", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FantasyTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("coach")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FantasyTeamId");

                    b.ToTable("FantasyCoaches");
                });

            modelBuilder.Entity("FantasyApi.Models.FantasyCoachRound", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("fantasyCoachId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("round")
                        .HasColumnType("int");

                    b.Property<double>("roundPoints")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("fantasyCoachId");

                    b.ToTable("FantasyCoachRounds");
                });

            modelBuilder.Entity("FantasyApi.Models.FantasyLeague", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("leagueAdminId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("leagueAdminId");

                    b.ToTable("FantasyLeagues");
                });

            modelBuilder.Entity("FantasyApi.Models.FantasyPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FantasyTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FantasyTeamId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FantasyTeamRoundId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FantasyTeamRoundId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("isInjured")
                        .HasColumnType("bit");

                    b.Property<Guid>("player")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FantasyTeamId");

                    b.HasIndex("FantasyTeamId1");

                    b.HasIndex("FantasyTeamRoundId");

                    b.HasIndex("FantasyTeamRoundId1");

                    b.ToTable("FantasyPlayers");
                });

            modelBuilder.Entity("FantasyApi.Models.FantasyPlayerRound", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("fantasyPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("round")
                        .HasColumnType("int");

                    b.Property<double>("roundPoints")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("fantasyPlayerId");

                    b.ToTable("FantasyPlayerRounds");
                });

            modelBuilder.Entity("FantasyApi.Models.FantasyTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FantasyLeagueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LeagueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("fantasyPlayerCaptainId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FantasyLeagueId");

                    b.HasIndex("UserId");

                    b.HasIndex("fantasyPlayerCaptainId");

                    b.ToTable("FantasyTeams");
                });

            modelBuilder.Entity("FantasyApi.Models.FantasyTeamRound", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("fantasyCoachId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("fantasyPlayerCaptainId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("fantasyTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("round")
                        .HasColumnType("int");

                    b.Property<double>("roundPoints")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("fantasyCoachId");

                    b.HasIndex("fantasyPlayerCaptainId");

                    b.HasIndex("fantasyTeamId");

                    b.ToTable("FantasyTeamRounds");
                });

            modelBuilder.Entity("FantasyApi.Models.Person", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("ForgotPasswordExp")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TokenForgotPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateOnly>("dateOfBirth")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("FantasyApi.Models.PlayerImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("PlayerImages");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityPasskeyData", b =>
                {
                    b.Property<byte[]>("AttestationObject")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("ClientDataJson")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsBackedUp")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBackupEligible")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUserVerified")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<long>("SignCount")
                        .HasColumnType("bigint");

                    b.PrimitiveCollection<string>("Transports")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FantasyApi.Models.FantasyCoach", b =>
                {
                    b.HasOne("FantasyApi.Models.FantasyTeam", null)
                        .WithMany("fantasyCoach")
                        .HasForeignKey("FantasyTeamId");
                });

            modelBuilder.Entity("FantasyApi.Models.FantasyCoachRound", b =>
                {
                    b.HasOne("FantasyApi.Models.FantasyCoach", "fantasyCoach")
                        .WithMany()
                        .HasForeignKey("fantasyCoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("fantasyCoach");
                });

            modelBuilder.Entity("FantasyApi.Models.FantasyLeague", b =>
                {
                    b.HasOne("FantasyApi.Models.Person", "leagueAdmin")
                        .WithMany()
                        .HasForeignKey("leagueAdminId");

                    b.Navigation("leagueAdmin");
                });

            modelBuilder.Entity("FantasyApi.Models.FantasyPlayer", b =>
                {
                    b.HasOne("FantasyApi.Models.FantasyTeam", null)
                        .WithMany("fantasyPlayersBench")
                        .HasForeignKey("FantasyTeamId");

                    b.HasOne("FantasyApi.Models.FantasyTeam", null)
                        .WithMany("fantasyPlayersStart")
                        .HasForeignKey("FantasyTeamId1");

                    b.HasOne("FantasyApi.Models.FantasyTeamRound", null)
                        .WithMany("fantasyPlayersBench")
                        .HasForeignKey("FantasyTeamRoundId");

                    b.HasOne("FantasyApi.Models.FantasyTeamRound", null)
                        .WithMany("fantasyPlayersStart")
                        .HasForeignKey("FantasyTeamRoundId1");
                });

            modelBuilder.Entity("FantasyApi.Models.FantasyPlayerRound", b =>
                {
                    b.HasOne("FantasyApi.Models.FantasyPlayer", "fantasyPlayer")
                        .WithMany()
                        .HasForeignKey("fantasyPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("fantasyPlayer");
                });

            modelBuilder.Entity("FantasyApi.Models.FantasyTeam", b =>
                {
                    b.HasOne("FantasyApi.Models.FantasyLeague", null)
                        .WithMany("fantasyTeams")
                        .HasForeignKey("FantasyLeagueId");

                    b.HasOne("FantasyApi.Models.Person", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.HasOne("FantasyApi.Models.FantasyPlayer", "fantasyPlayerCaptain")
                        .WithMany()
                        .HasForeignKey("fantasyPlayerCaptainId");

                    b.Navigation("User");

                    b.Navigation("fantasyPlayerCaptain");
                });

            modelBuilder.Entity("FantasyApi.Models.FantasyTeamRound", b =>
                {
                    b.HasOne("FantasyApi.Models.FantasyCoach", "fantasyCoach")
                        .WithMany()
                        .HasForeignKey("fantasyCoachId");

                    b.HasOne("FantasyApi.Models.FantasyPlayer", "fantasyPlayerCaptain")
                        .WithMany()
                        .HasForeignKey("fantasyPlayerCaptainId");

                    b.HasOne("FantasyApi.Models.FantasyTeam", "fantasyTeam")
                        .WithMany()
                        .HasForeignKey("fantasyTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("fantasyCoach");

                    b.Navigation("fantasyPlayerCaptain");

                    b.Navigation("fantasyTeam");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FantasyApi.Models.Person", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FantasyApi.Models.Person", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FantasyApi.Models.Person", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FantasyApi.Models.Person", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FantasyApi.Models.FantasyLeague", b =>
                {
                    b.Navigation("fantasyTeams");
                });

            modelBuilder.Entity("FantasyApi.Models.FantasyTeam", b =>
                {
                    b.Navigation("fantasyCoach");

                    b.Navigation("fantasyPlayersBench");

                    b.Navigation("fantasyPlayersStart");
                });

            modelBuilder.Entity("FantasyApi.Models.FantasyTeamRound", b =>
                {
                    b.Navigation("fantasyPlayersBench");

                    b.Navigation("fantasyPlayersStart");
                });
#pragma warning restore 612, 618
        }
    }
}
